languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false
exclude_paths:
  - "dist-commonjs"
  - "dist-esmodule"
  - "dist-umd"
engines:
  tslint:
    enabled: true
    channel: beta
    checks:
      eofline:
        enabled: false
      array-type:
        enabled: false
      max-line-length:
        enabled: false
      max-classes-per-file:
        enabled: false